"""
Translation strings for backend report generation (BOQ sections, export labels).

Supports: English (en), Turkish (tr), Arabic (ar).
"""

from __future__ import annotations

from typing import Any


# BOQ section titles keyed by ElementCategory.value
BOQ_SECTIONS: dict[str, dict[str, str]] = {
    "en": {
        "substructure": "Substructure",
        "frame": "Structural Frame (Columns & Beams)",
        "external_walls": "External Walls",
        "internal_walls": "Internal Walls & Partitions",
        "upper_floors": "Upper Floor Slabs",
        "roof": "Roof",
        "doors": "Doors",
        "windows": "Windows",
        "stairs": "Stairs & Ramps",
        "finishes": "Finishes",
        "mep": "Mechanical, Electrical & Plumbing",
        "external_works": "External Works",
        "other": "Other Items",
    },
    "tr": {
        "substructure": "Altyap\u0131",
        "frame": "Ta\u015f\u0131y\u0131c\u0131 Sistem (Kolon ve Kiri\u015fler)",
        "external_walls": "D\u0131\u015f Duvarlar",
        "internal_walls": "I\u0307\u00e7 Duvarlar ve B\u00f6lmeler",
        "upper_floors": "\u00dcst Kat D\u00f6\u015femeleri",
        "roof": "\u00c7at\u0131",
        "doors": "Kap\u0131lar",
        "windows": "Pencereler",
        "stairs": "Merdivenler ve Rampalar",
        "finishes": "I\u0307nce I\u0307\u015fler",
        "mep": "Mekanik, Elektrik ve Tesisat",
        "external_works": "D\u0131\u015f I\u0307\u015fler",
        "other": "Di\u011fer Kalemler",
    },
    "ar": {
        "substructure": "\u0627\u0644\u0628\u0646\u064a\u0629 \u0627\u0644\u062a\u062d\u062a\u064a\u0629",
        "frame": "\u0627\u0644\u0647\u064a\u0643\u0644 \u0627\u0644\u0625\u0646\u0634\u0627\u0626\u064a (\u0627\u0644\u0623\u0639\u0645\u062f\u0629 \u0648\u0627\u0644\u062c\u0633\u0648\u0631)",
        "external_walls": "\u0627\u0644\u062c\u062f\u0631\u0627\u0646 \u0627\u0644\u062e\u0627\u0631\u062c\u064a\u0629",
        "internal_walls": "\u0627\u0644\u062c\u062f\u0631\u0627\u0646 \u0627\u0644\u062f\u0627\u062e\u0644\u064a\u0629 \u0648\u0627\u0644\u0641\u0648\u0627\u0635\u0644",
        "upper_floors": "\u0628\u0644\u0627\u0637\u0627\u062a \u0627\u0644\u0637\u0648\u0627\u0628\u0642 \u0627\u0644\u0639\u0644\u0648\u064a\u0629",
        "roof": "\u0627\u0644\u0633\u0642\u0641",
        "doors": "\u0627\u0644\u0623\u0628\u0648\u0627\u0628",
        "windows": "\u0627\u0644\u0646\u0648\u0627\u0641\u0630",
        "stairs": "\u0627\u0644\u0633\u0644\u0627\u0644\u0645 \u0648\u0627\u0644\u0645\u0646\u062d\u062f\u0631\u0627\u062a",
        "finishes": "\u0627\u0644\u062a\u0634\u0637\u064a\u0628\u0627\u062a",
        "mep": "\u0627\u0644\u0623\u0639\u0645\u0627\u0644 \u0627\u0644\u0645\u064a\u0643\u0627\u0646\u064a\u0643\u064a\u0629 \u0648\u0627\u0644\u0643\u0647\u0631\u0628\u0627\u0626\u064a\u0629 \u0648\u0627\u0644\u0635\u062d\u064a\u0629",
        "external_works": "\u0627\u0644\u0623\u0639\u0645\u0627\u0644 \u0627\u0644\u062e\u0627\u0631\u062c\u064a\u0629",
        "other": "\u0628\u0646\u0648\u062f \u0623\u062e\u0631\u0649",
    },
}


EXPORT_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "boq_title": "BILL OF QUANTITIES",
        "material_summary": "MATERIAL SUMMARY",
        "sheet_boq": "Bill of Quantities",
        "sheet_summary": "Material Summary",
        "project": "Project",
        "building": "Building",
        "date": "Date",
        "prepared_by": "Prepared by",
        "item_no": "Item No.",
        "description": "Description",
        "unit": "Unit",
        "quantity": "Quantity",
        "rate": "Rate",
        "amount": "Amount",
        "section": "Section",
        "no": "No.",
        "material": "Material",
        "total_qty": "Total Qty",
        "category": "Category",
        "footer": "Generated by Metraj AI - Construction Material Estimation System",
        "subtotal": "Subtotal",
        "grand_total": "GRAND TOTAL",
        "sheet_audit": "Audit Trail",
        "audit_title": "QUANTITY AUDIT TRAIL",
        "base_qty": "Base Qty",
        "waste_pct": "Waste %",
        "total_qty_with_waste": "Total Qty (incl. waste)",
        "source_elements_count": "Source Elements",
    },
    "tr": {
        "boq_title": "METRAJ L\u0130STES\u0130",
        "material_summary": "MALZEME \u00d6ZET\u0130",
        "sheet_boq": "Metraj Listesi",
        "sheet_summary": "Malzeme \u00d6zeti",
        "project": "Proje",
        "building": "Bina",
        "date": "Tarih",
        "prepared_by": "Haz\u0131rlayan",
        "item_no": "S\u0131ra No.",
        "description": "A\u00e7\u0131klama",
        "unit": "Birim",
        "quantity": "Miktar",
        "rate": "Birim Fiyat",
        "amount": "Tutar",
        "section": "B\u00f6l\u00fcm",
        "no": "No.",
        "material": "Malzeme",
        "total_qty": "Toplam Miktar",
        "category": "Kategori",
        "footer": "Metraj AI - Yap\u0131 Malzeme Tahmin Sistemi taraf\u0131ndan olu\u015fturuldu",
        "subtotal": "Ara Toplam",
        "grand_total": "GENEL TOPLAM",
        "sheet_audit": "Denetim \u0130zi",
        "audit_title": "M\u0130KTAR DENET\u0130M \u0130Z\u0130",
        "base_qty": "Temel Miktar",
        "waste_pct": "Fire %",
        "total_qty_with_waste": "Toplam Miktar (fire dahil)",
        "source_elements_count": "Kaynak Elemanlar",
    },
    "ar": {
        "boq_title": "\u062c\u062f\u0648\u0644 \u0627\u0644\u0643\u0645\u064a\u0627\u062a",
        "material_summary": "\u0645\u0644\u062e\u0635 \u0627\u0644\u0645\u0648\u0627\u062f",
        "sheet_boq": "\u062c\u062f\u0648\u0644 \u0627\u0644\u0643\u0645\u064a\u0627\u062a",
        "sheet_summary": "\u0645\u0644\u062e\u0635 \u0627\u0644\u0645\u0648\u0627\u062f",
        "project": "\u0627\u0644\u0645\u0634\u0631\u0648\u0639",
        "building": "\u0627\u0644\u0645\u0628\u0646\u0649",
        "date": "\u0627\u0644\u062a\u0627\u0631\u064a\u062e",
        "prepared_by": "\u0625\u0639\u062f\u0627\u062f",
        "item_no": "\u0631\u0642\u0645 \u0627\u0644\u0628\u0646\u062f",
        "description": "\u0627\u0644\u0648\u0635\u0641",
        "unit": "\u0627\u0644\u0648\u062d\u062f\u0629",
        "quantity": "\u0627\u0644\u0643\u0645\u064a\u0629",
        "rate": "\u0627\u0644\u0633\u0639\u0631",
        "amount": "\u0627\u0644\u0645\u0628\u0644\u063a",
        "section": "\u0627\u0644\u0642\u0633\u0645",
        "no": "\u0645.",
        "material": "\u0627\u0644\u0645\u0627\u062f\u0629",
        "total_qty": "\u0627\u0644\u0643\u0645\u064a\u0629 \u0627\u0644\u0625\u062c\u0645\u0627\u0644\u064a\u0629",
        "category": "\u0627\u0644\u0641\u0626\u0629",
        "footer": "\u062a\u0645 \u0625\u0646\u0634\u0627\u0624\u0647 \u0628\u0648\u0627\u0633\u0637\u0629 Metraj AI - \u0646\u0638\u0627\u0645 \u062a\u0642\u062f\u064a\u0631 \u0645\u0648\u0627\u062f \u0627\u0644\u0628\u0646\u0627\u0621",
        "subtotal": "\u0627\u0644\u0645\u062c\u0645\u0648\u0639 \u0627\u0644\u0641\u0631\u0639\u064a",
        "grand_total": "\u0627\u0644\u0645\u062c\u0645\u0648\u0639 \u0627\u0644\u0643\u0644\u064a",
        "sheet_audit": "\u0645\u0633\u0627\u0631 \u0627\u0644\u062a\u062f\u0642\u064a\u0642",
        "audit_title": "\u0645\u0633\u0627\u0631 \u062a\u062f\u0642\u064a\u0642 \u0627\u0644\u0643\u0645\u064a\u0627\u062a",
        "base_qty": "\u0627\u0644\u0643\u0645\u064a\u0629 \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0629",
        "waste_pct": "\u0646\u0633\u0628\u0629 \u0627\u0644\u0647\u062f\u0631 %",
        "total_qty_with_waste": "\u0627\u0644\u0643\u0645\u064a\u0629 \u0627\u0644\u0625\u062c\u0645\u0627\u0644\u064a\u0629 (\u0634\u0627\u0645\u0644 \u0627\u0644\u0647\u062f\u0631)",
        "source_elements_count": "\u0639\u0646\u0627\u0635\u0631 \u0627\u0644\u0645\u0635\u062f\u0631",
    },
}


def get_boq_sections(language: str = "en") -> dict[str, str]:
    """Get BOQ section titles for a language."""
    return BOQ_SECTIONS.get(language, BOQ_SECTIONS["en"])


def get_export_labels(language: str = "en") -> dict[str, str]:
    """Get export labels for a language."""
    return EXPORT_LABELS.get(language, EXPORT_LABELS["en"])
