"""
Tests for the IFC Parser Agent and IFC Service.

These tests use the sample IFC file generated by scripts/create_sample_ifc.py.
The sample house has: 13 walls, 3 slabs, 12 columns, 10 beams, 8 doors, 10 windows.
"""

import asyncio
from pathlib import Path

import pytest

from src.models.project import ProcessingStatus
from src.services.ifc_service import IFCService
from src.agents.ifc_parser import IFCParserAgent

FIXTURES_DIR = Path(__file__).parent / "fixtures"
SAMPLE_IFC = FIXTURES_DIR / "simple_house.ifc"


# ------------------------------------------------------------------
# IFC Service Tests
# ------------------------------------------------------------------

class TestIFCService:
    """Tests for the low-level IFC service wrapper."""

    def setup_method(self):
        self.service = IFCService(SAMPLE_IFC)

    def test_open_file(self):
        assert self.service.model is not None
        assert self.service.model.schema == "IFC4"

    def test_get_project_info(self):
        info = self.service.get_project_info()
        assert info["project_name"] == "Sample House"
        assert info["building_name"] == "Sample House"
        assert info["site_name"] == "Construction Site"
        assert info["total_entities"] > 0

    def test_get_storeys(self):
        storeys = self.service.get_storeys()
        assert len(storeys) == 2
        assert storeys[0]["name"] == "Ground Floor"
        assert storeys[0]["elevation"] == 0.0
        assert storeys[1]["name"] == "First Floor"
        assert storeys[1]["elevation"] == 3.0

    def test_count_elements_by_type(self):
        counts = self.service.count_elements_by_type()
        assert counts["IfcWall"] == 13
        assert counts["IfcSlab"] == 3
        assert counts["IfcColumn"] == 12
        assert counts["IfcBeam"] == 10
        assert counts["IfcDoor"] == 8
        assert counts["IfcWindow"] == 10

    def test_get_elements_by_type(self):
        walls = self.service.get_elements_by_type("IfcWall")
        assert len(walls) == 13

    def test_get_all_building_elements(self):
        elements = self.service.get_all_building_elements()
        assert len(elements) == 56  # 13+3+12+10+8+10

    def test_get_element_quantities(self):
        walls = self.service.get_elements_by_type("IfcWall")
        wall = walls[0]
        quantities = self.service.get_element_quantities(wall)
        assert "Length" in quantities
        assert "Height" in quantities
        assert "GrossArea" in quantities
        assert "GrossVolume" in quantities
        assert quantities["Length"] == 10.0
        assert quantities["Height"] == 3.0

    def test_get_element_properties(self):
        walls = self.service.get_elements_by_type("IfcWall")
        wall = walls[0]
        props = self.service.get_element_properties(wall)
        assert "IsExternal" in props
        assert props["IsExternal"] is True

    def test_get_element_material(self):
        walls = self.service.get_elements_by_type("IfcWall")
        wall = walls[0]
        materials = self.service.get_element_material(wall)
        assert len(materials) > 0
        assert "Concrete C25/30" in materials

    def test_get_element_container(self):
        walls = self.service.get_elements_by_type("IfcWall")
        wall = walls[0]
        storey = self.service.get_element_container(wall)
        assert storey == "Ground Floor"

    def test_extract_element_data(self):
        walls = self.service.get_elements_by_type("IfcWall")
        data = self.service.extract_element_data(walls[0])
        assert data["ifc_type"] == "IfcWall"
        assert data["name"] is not None
        assert len(data["quantities"]) > 0
        assert len(data["materials"]) > 0
        assert data["storey"] is not None
        assert data["is_external"] is True

    def test_extract_all_elements(self):
        all_data = self.service.extract_all_elements()
        assert len(all_data) == 56

    def test_file_not_found(self):
        with pytest.raises(FileNotFoundError):
            IFCService("nonexistent.ifc")


# ------------------------------------------------------------------
# IFC Parser Agent Tests
# ------------------------------------------------------------------

class TestIFCParserAgent:
    """Tests for the IFC Parser Agent."""

    def test_parser_executes(self):
        agent = IFCParserAgent()
        state = {
            "ifc_file_path": str(SAMPLE_IFC),
            "project_config": {},
            "parsed_elements": [],
            "building_info": None,
            "classified_elements": {},
            "calculated_quantities": [],
            "material_list": [],
            "boq_data": None,
            "boq_file_paths": {},
            "validation_report": None,
            "warnings": [],
            "errors": [],
            "status": ProcessingStatus.PENDING,
            "current_step": "",
            "processing_log": [],
        }

        result = asyncio.run(agent.execute(state))

        # Building info should be populated
        assert result["building_info"] is not None
        assert result["building_info"]["project_name"] == "Sample House"
        assert len(result["building_info"]["storeys"]) == 2

        # All 56 elements should be parsed
        assert len(result["parsed_elements"]) == 56

        # Check that elements have the right structure
        first_elem = result["parsed_elements"][0]
        assert "ifc_id" in first_elem
        assert "ifc_type" in first_elem
        assert "quantities" in first_elem
        assert "materials" in first_elem

        # Processing log should have an entry
        assert len(result["processing_log"]) > 0

    def test_parser_handles_missing_file(self):
        agent = IFCParserAgent()
        state = {
            "ifc_file_path": "nonexistent.ifc",
            "project_config": {},
            "parsed_elements": [],
            "building_info": None,
            "classified_elements": {},
            "calculated_quantities": [],
            "material_list": [],
            "boq_data": None,
            "boq_file_paths": {},
            "validation_report": None,
            "warnings": [],
            "errors": [],
            "status": ProcessingStatus.PENDING,
            "current_step": "",
            "processing_log": [],
        }

        result = asyncio.run(agent.execute(state))
        assert result["status"] == ProcessingStatus.FAILED
        assert len(result["errors"]) > 0
